dist: xenial

language: python

python:
  - "3.6"

env:
  - WAGTAIL_VERSION='>=2.3,<2.4'
  - WAGTAIL_VERSION='>=2.7,<2.8'
  - WAGTAIL_VERSION='>=2.8,<2.9'
  - WAGTAIL_VERSION='>=2.9,<2.10'

cache: pip

install:
  - pip install -e .
  - pip install wagtail$WAGTAIL_VERSION

script:
  - ./runtests.py
