dist: xenial

language: python

python:
  - "3.6"

env:
  - WAGTAIL_VERSION=2.0.2
  - WAGTAIL_VERSION=2.1.3
  - WAGTAIL_VERSION=2.2.2
  - WAGTAIL_VERSION=2.3
  - WAGTAIL_VERSION=2.4
  - WAGTAIL_VERSION=2.5.2
  - WAGTAIL_VERSION=2.6.3
  - WAGTAIL_VERSION=2.7.3
  - WAGTAIL_VERSION=2.8.2
  - WAGTAIL_VERSION=2.9.2

cache: pip

install:
  - pip install -e .
  - pip install wagtail==$WAGTAIL_VERSION

script:
  - ./runtests.py
